name: tb2
channels:
  - conda-forge
  - fastai
  - nodefaults
dependencies:
  - arviz
  - html5lib
  - jupyter
  - jupyterlab
  - lxml
  - matplotlib
  - mkl-service
  - numpy
  - pandas
  - pymc3
  - pytables
  - python>=3.12
  - python-graphviz
  - scipy
  - seaborn
  - statsmodels
  - xlrd
  - nbconvert
  - pandoc<2.3
  - fastai::fastdoc
  - pip
  - jupyter_nbextensions_configurator
  - pytest
  - nbmake
  - jupyter-book
  - ghp-import
  - empiricaldist
